mini:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  torso_upper_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_upper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  head_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  wrist_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  finger_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  finger_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

