<?xml version="1.0" encoding="utf-8"?>

<robot name="finger_right" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define a number of dimensions using properties -->
  <property name="finger_right_offset_x" value="0.112" />
  <property name="finger_right_offset_y" value="-0.048" />
  <property name="finger_right_offset_z" value="0.01" />
  <property name="finger_radius" value="0.025" />
  <property name="finger_length" value="0.1" />
     
  <!-- Define the torso -->
  <macro name="finger_right" params="parent name">
    <joint name="${name}_joint" type="revolute">
      <origin xyz="${finger_right_offset_x} ${finger_right_offset_y} ${finger_right_offset_z}" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
      <limit effort="1.0" lower="-1.5" upper="1.5" velocity="1.571"/>
      <parent link="${parent}_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 iyy="1.0" iyz="0.0"
                 izz="1.0" />
      </inertial>

      <visual>
	<!-- <origin xyz="-0.01 0.015 0.005" rpy="0 ${M_PI/2} 0" /> -->
	<!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
	<origin xyz="-0.15 -0.05  -0.475" rpy="${-20*M_PI/180} 0 ${M_PI/2}" />
	<geometry>
	  <mesh filename="package://mini_description/meshes/mini1.5/mini2_finger_right_module.dae" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}" />
	</geometry>
	<!-- <material color="yellow"/> -->
      </visual>
      <collision>
        <!-- <origin xyz="${finger_left_offset_x-0.02} ${finger_left_offset_y-0.08}
                     ${finger_left_offset_z-0.01}" rpy="0 ${M_PI/2} 0" /> -->
	<origin xyz="${finger_left_offset_x-0.025} ${finger_left_offset_y-0.09}
                     ${finger_left_offset_z-0.01}" rpy="0 ${M_PI/2} 0" />

        <geometry>
          <cylinder length="${finger_length}" radius="${finger_radius}" />
        </geometry>
      </collision> 

    </link>
  </macro>

</robot>
